services:

  postgres:
    image: postgres:16
    container_name: hrms-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: hrms_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5433:5432"

    volumes:
      - hrms-postgres-data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: hrms-api
    restart: unless-stopped

    depends_on:
      - postgres

    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8080
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=hrms_db;Username=postgres;Password=${POSTGRES_PASSWORD}"

    ports:
      - "8080:8080"

volumes:
  hrms-postgres-data: